// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://www.reqnroll.net/).
//      Reqnroll Version:2.0.0.0
//      Reqnroll Generator Version:2.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
using Reqnroll;
namespace ProjectMars_OnboardTask2.Features
{
    
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "2.0.0.0")]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("Language")]
    [NUnit.Framework.FixtureLifeCycleAttribute(NUnit.Framework.LifeCycle.InstancePerTestCase)]
    public partial class LanguageFeature
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new global::System.Globalization.CultureInfo("en-US"), "Features", "Language", "As a user I would like to add,edit and delete languages I know in a list\r\nso I ca" +
                "n showcase them under my profile page.", global::Reqnroll.ProgrammingLanguage.CSharp, featureTags);
        
#line 1 "Language.feature"
#line hidden
        
        [NUnit.Framework.OneTimeSetUpAttribute()]
        public static async global::System.Threading.Tasks.Task FeatureSetupAsync()
        {
        }
        
        [NUnit.Framework.OneTimeTearDownAttribute()]
        public static async global::System.Threading.Tasks.Task FeatureTearDownAsync()
        {
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public async global::System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            try
            {
                if (((testRunner.FeatureContext != null) 
                            && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
                {
                    await testRunner.OnFeatureEndAsync();
                }
            }
            finally
            {
                if (((testRunner.FeatureContext != null) 
                            && testRunner.FeatureContext.BeforeFeatureHookFailed))
                {
                    throw new global::Reqnroll.ReqnrollException("Scenario skipped because of previous before feature hook error");
                }
                if ((testRunner.FeatureContext == null))
                {
                    await testRunner.OnFeatureStartAsync(featureInfo);
                }
            }
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public async global::System.Threading.Tasks.Task TestTearDownAsync()
        {
            if ((testRunner == null))
            {
                return;
            }
            try
            {
                await testRunner.OnScenarioEndAsync();
            }
            finally
            {
                global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
                testRunner = null;
            }
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<NUnit.Framework.TestContext>(NUnit.Framework.TestContext.CurrentContext);
        }
        
        public async global::System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async global::System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Add new languaage with valid details")]
        [NUnit.Framework.CategoryAttribute("positive")]
        [NUnit.Framework.CategoryAttribute("RequiresSignIn")]
        [NUnit.Framework.CategoryAttribute("LanguageCleanup")]
        [NUnit.Framework.TestCaseAttribute("TC022", "English", "Fluent", "has been added to your languages", null)]
        [NUnit.Framework.TestCaseAttribute("TC022", "Tagalog", "Fluent", "has been added to your languages", null)]
        public async global::System.Threading.Tasks.Task AddNewLanguaageWithValidDetails(string testCaseID, string language, string level, string message, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "positive",
                    "RequiresSignIn",
                    "LanguageCleanup"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            string[] tagsOfScenario = @__tags;
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("testCaseID", testCaseID);
            argumentsOfScenario.Add("language", language);
            argumentsOfScenario.Add("level", level);
            argumentsOfScenario.Add("message", message);
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Add new languaage with valid details", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 8
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 9
 await testRunner.GivenAsync("I am in the Language section of my profile", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 10
 await testRunner.WhenAsync(string.Format("I add \"{0}\" and \"{1}\"", language, level), ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 11
 await testRunner.ThenAsync(string.Format("successful added \"{0}\" \"{1}\" should be displayed", language, message), ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 12
 await testRunner.AndAsync(string.Format("\"{0}\" and \"{1}\" should appear in my language list", language, level), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Add new language with invalid details")]
        [NUnit.Framework.CategoryAttribute("negative")]
        [NUnit.Framework.CategoryAttribute("RequiresSignIn")]
        [NUnit.Framework.CategoryAttribute("LanguageCleanup")]
        [NUnit.Framework.TestCaseAttribute("TC023", "", "Basic", "Please enter language and level", null)]
        [NUnit.Framework.TestCaseAttribute("TC024", "French", "Choose Language Level", "Please enter language and level", null)]
        public async global::System.Threading.Tasks.Task AddNewLanguageWithInvalidDetails(string testCaseID, string language, string level, string message, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "negative",
                    "RequiresSignIn",
                    "LanguageCleanup"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            string[] tagsOfScenario = @__tags;
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("testCaseID", testCaseID);
            argumentsOfScenario.Add("language", language);
            argumentsOfScenario.Add("level", level);
            argumentsOfScenario.Add("message", message);
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Add new language with invalid details", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 21
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 22
await testRunner.GivenAsync("I am in the Language section of my profile", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 23
await testRunner.WhenAsync(string.Format("I add \"{0}\" and \"{1}\"", language, level), ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 24
await testRunner.ThenAsync(string.Format("an error \"{0}\" should be displayed", message), ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Add duplicate language record")]
        [NUnit.Framework.CategoryAttribute("TC025")]
        [NUnit.Framework.CategoryAttribute("negative")]
        [NUnit.Framework.CategoryAttribute("RequiresSignIn")]
        [NUnit.Framework.CategoryAttribute("LanguageCleanup")]
        public async global::System.Threading.Tasks.Task AddDuplicateLanguageRecord()
        {
            string[] tagsOfScenario = new string[] {
                    "TC025",
                    "negative",
                    "RequiresSignIn",
                    "LanguageCleanup"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Add duplicate language record", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 33
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 34
await testRunner.GivenAsync("I am in the Language section of my profile", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 35
await testRunner.WhenAsync("I add \"English\" and \"Fluent\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 36
await testRunner.AndAsync("I recreate same language record \"English\" and \"Fluent\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 37
await testRunner.ThenAsync("an error \"This language is already exist in your language list.\" should be displa" +
                        "yed", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Edit Language record with valid details")]
        [NUnit.Framework.CategoryAttribute("positive")]
        [NUnit.Framework.CategoryAttribute("RequiresSignIn")]
        [NUnit.Framework.CategoryAttribute("LanguageCleanup")]
        [NUnit.Framework.TestCaseAttribute("TC028", "English", "French", "Fluent", "Basic", "has been updated to your languages", null)]
        public async global::System.Threading.Tasks.Task EditLanguageRecordWithValidDetails(string testCaseID, string languageOld, string languageNew, string levelOld, string levelNew, string message, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "positive",
                    "RequiresSignIn",
                    "LanguageCleanup"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            string[] tagsOfScenario = @__tags;
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("testCaseID", testCaseID);
            argumentsOfScenario.Add("languageOld", languageOld);
            argumentsOfScenario.Add("languageNew", languageNew);
            argumentsOfScenario.Add("levelOld", levelOld);
            argumentsOfScenario.Add("levelNew", levelNew);
            argumentsOfScenario.Add("message", message);
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Edit Language record with valid details", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 40
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 41
await testRunner.GivenAsync("I am in the Language section of my profile", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 42
await testRunner.WhenAsync("I successfully add \"English\" and \"Fluent\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 43
await testRunner.AndAsync(string.Format("I edit \"{0}\" to \"{1}\" and/or \"{2}\" to \"{3}\"", languageOld, languageNew, levelOld, levelNew), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 44
await testRunner.ThenAsync(string.Format("successful update message \"{0}\" \"{1}\" should appear", languageNew, message), ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 45
await testRunner.AndAsync(string.Format("updated \"{0}\" and/or \"{1}\" should be shown  in the list", languageNew, levelNew), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Edit duplicate Language record")]
        [NUnit.Framework.CategoryAttribute("TC029")]
        [NUnit.Framework.CategoryAttribute("negative")]
        [NUnit.Framework.CategoryAttribute("RequiresSignIn")]
        [NUnit.Framework.CategoryAttribute("LanguageCleanup")]
        [NUnit.Framework.TestCaseAttribute("TC029", "Tagalog", "French", "Native/Bilingual", "Fluent", "This language is already added to your language list.", null)]
        public async global::System.Threading.Tasks.Task EditDuplicateLanguageRecord(string testCaseID, string languageOld, string languageNew, string levelOld, string levelNew, string message, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "TC029",
                    "negative",
                    "RequiresSignIn",
                    "LanguageCleanup"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            string[] tagsOfScenario = @__tags;
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("testCaseID", testCaseID);
            argumentsOfScenario.Add("languageOld", languageOld);
            argumentsOfScenario.Add("languageNew", languageNew);
            argumentsOfScenario.Add("levelOld", levelOld);
            argumentsOfScenario.Add("levelNew", levelNew);
            argumentsOfScenario.Add("message", message);
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Edit duplicate Language record", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 53
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 54
await testRunner.GivenAsync("I am in the Language section of my profile", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 55
await testRunner.WhenAsync("I successfully add \"Tagalog\" and \"Native/Bilingual\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 56
await testRunner.AndAsync("I successfully add \"French\" and \"Fluent\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 57
await testRunner.AndAsync(string.Format("I verify the language \"{0}\" with level \"{1}\" exists", languageOld, levelOld), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 58
await testRunner.WhenAsync(string.Format("I edit \"{0}\" to \"{1}\" and/or \"{2}\" to \"{3}\"", languageOld, languageNew, levelOld, levelNew), ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 59
await testRunner.ThenAsync(string.Format("an error \"{0}\" should be displayed", message), ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Edit Language record with invalid details")]
        [NUnit.Framework.CategoryAttribute("negative")]
        [NUnit.Framework.CategoryAttribute("RequiresSignIn")]
        [NUnit.Framework.CategoryAttribute("LanguageCleanup")]
        [NUnit.Framework.TestCaseAttribute("TC031", "Tagalog", "", "Native/Bilingual", "Fluent", "Please enter language and level", null)]
        [NUnit.Framework.TestCaseAttribute("TC032", "Tagalog", "English", "Native/Bilingual", "Language Level", "Please enter language and level", null)]
        public async global::System.Threading.Tasks.Task EditLanguageRecordWithInvalidDetails(string testCaseID, string languageOld, string languageNew, string levelOld, string levelNew, string message, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "negative",
                    "RequiresSignIn",
                    "LanguageCleanup"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            string[] tagsOfScenario = @__tags;
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("testCaseID", testCaseID);
            argumentsOfScenario.Add("languageOld", languageOld);
            argumentsOfScenario.Add("languageNew", languageNew);
            argumentsOfScenario.Add("levelOld", levelOld);
            argumentsOfScenario.Add("levelNew", levelNew);
            argumentsOfScenario.Add("message", message);
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Edit Language record with invalid details", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 66
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 67
await testRunner.GivenAsync("I am in the Language section of my profile", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 68
await testRunner.WhenAsync("I successfully add \"Tagalog\" and \"Native/Bilingual\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 69
await testRunner.AndAsync(string.Format("I verify the language \"{0}\" with level \"{1}\" exists", languageOld, levelOld), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 70
await testRunner.WhenAsync(string.Format("I edit \"{0}\" to \"{1}\" and/or \"{2}\" to \"{3}\"", languageOld, languageNew, levelOld, levelNew), ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 71
await testRunner.ThenAsync(string.Format("an error \"{0}\" should be displayed", message), ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Delete language record")]
        [NUnit.Framework.CategoryAttribute("positive")]
        [NUnit.Framework.CategoryAttribute("RequiresSignIn")]
        [NUnit.Framework.CategoryAttribute("LanguageCleanup")]
        [NUnit.Framework.TestCaseAttribute("TC035", "English", "Fluent", "has been deleted", null)]
        [NUnit.Framework.TestCaseAttribute("TC035", "Tagalog", "Fluent", "has been deleted", null)]
        public async global::System.Threading.Tasks.Task DeleteLanguageRecord(string testCaseID, string language, string level, string message, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "positive",
                    "RequiresSignIn",
                    "LanguageCleanup"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            string[] tagsOfScenario = @__tags;
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("testCaseID", testCaseID);
            argumentsOfScenario.Add("language", language);
            argumentsOfScenario.Add("level", level);
            argumentsOfScenario.Add("message", message);
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Delete language record", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 80
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 81
await testRunner.GivenAsync("I am in the Language section of my profile", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 82
await testRunner.WhenAsync(string.Format("I successfully add \"{0}\" and \"{1}\"", language, level), ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 83
await testRunner.AndAsync(string.Format("I verify the language \"{0}\" with level \"{1}\" exists", language, level), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 84
await testRunner.WhenAsync(string.Format("I delete existing  \"{0}\" with \"{1}\" record", language, level), ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 85
await testRunner.ThenAsync(string.Format("successful deleted \"{0}\"  \"{1}\" should be displayed", language, message), ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 86
await testRunner.AndAsync(string.Format("\"{0}\" with \"{1}\" record should be removed from the list", language, level), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
    }
}
#pragma warning restore
#endregion
