// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://www.reqnroll.net/).
//      Reqnroll Version:2.0.0.0
//      Reqnroll Generator Version:2.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
using Reqnroll;
namespace ProjectMars_OnboardTask2.Features
{
    
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "2.0.0.0")]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("Skill")]
    [NUnit.Framework.FixtureLifeCycleAttribute(NUnit.Framework.LifeCycle.InstancePerTestCase)]
    public partial class SkillFeature
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new global::System.Globalization.CultureInfo("en-US"), "Features", "Skill", "A short summary of the feature\r\n\r\nAs a user I would like to add,edit and delete s" +
                "kills I know in a list\r\nso I can showcase them under my profile page.", global::Reqnroll.ProgrammingLanguage.CSharp, featureTags);
        
#line 1 "Skill.feature"
#line hidden
        
        [NUnit.Framework.OneTimeSetUpAttribute()]
        public static async global::System.Threading.Tasks.Task FeatureSetupAsync()
        {
        }
        
        [NUnit.Framework.OneTimeTearDownAttribute()]
        public static async global::System.Threading.Tasks.Task FeatureTearDownAsync()
        {
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public async global::System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            try
            {
                if (((testRunner.FeatureContext != null) 
                            && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
                {
                    await testRunner.OnFeatureEndAsync();
                }
            }
            finally
            {
                if (((testRunner.FeatureContext != null) 
                            && testRunner.FeatureContext.BeforeFeatureHookFailed))
                {
                    throw new global::Reqnroll.ReqnrollException("Scenario skipped because of previous before feature hook error");
                }
                if ((testRunner.FeatureContext == null))
                {
                    await testRunner.OnFeatureStartAsync(featureInfo);
                }
            }
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public async global::System.Threading.Tasks.Task TestTearDownAsync()
        {
            if ((testRunner == null))
            {
                return;
            }
            try
            {
                await testRunner.OnScenarioEndAsync();
            }
            finally
            {
                global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
                testRunner = null;
            }
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<NUnit.Framework.TestContext>(NUnit.Framework.TestContext.CurrentContext);
        }
        
        public async global::System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async global::System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        public virtual async global::System.Threading.Tasks.Task FeatureBackgroundAsync()
        {
#line 9
#line hidden
#line 10
 await testRunner.GivenAsync("I am in the sign in page", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 11
 await testRunner.WhenAsync("I enter valid \"charie_artz@yahoo.com\" and valid \"P@ssw0rd\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 12
 await testRunner.ThenAsync("I should see my profile page with greeting \"Hi Charito\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Add new skill with valid details")]
        [NUnit.Framework.CategoryAttribute("positive")]
        [NUnit.Framework.TestCaseAttribute("TC036", "Communication", "Intermediate", "has been added to your skills", null)]
        [NUnit.Framework.TestCaseAttribute("TC036", "Writing", "Expert", "has been added to your skills", null)]
        public async global::System.Threading.Tasks.Task AddNewSkillWithValidDetails(string testCaseID, string skill, string level, string message, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "positive"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            string[] tagsOfScenario = @__tags;
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("testCaseID", testCaseID);
            argumentsOfScenario.Add("skill", skill);
            argumentsOfScenario.Add("level", level);
            argumentsOfScenario.Add("message", message);
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Add new skill with valid details", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 15
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 9
await this.FeatureBackgroundAsync();
#line hidden
#line 16
 await testRunner.GivenAsync("I am in the skill section of my profile", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 17
 await testRunner.WhenAsync(string.Format("I add new \"{0}\" and \"{1}\"", skill, level), ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 18
 await testRunner.ThenAsync(string.Format("successful add \"{0}\" \"{1}\" should be displayed", skill, message), ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 19
 await testRunner.AndAsync(string.Format("\"{0}\" and \"{1}\" should appear in my skill list", skill, level), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Add new skill with invalid details")]
        [NUnit.Framework.CategoryAttribute("negative")]
        [NUnit.Framework.TestCaseAttribute("TC037", "", "Beginner", "Please enter skill and experience level", null)]
        [NUnit.Framework.TestCaseAttribute("TC038", "Cooking", "Choose Skill Level", "Please enter skill and experience level", null)]
        [NUnit.Framework.TestCaseAttribute("TC039", "Communication", "Intermediate", "This skill is already exist in your skill list.", null)]
        [NUnit.Framework.TestCaseAttribute("TC040", "Communication", "Beginner", "Duplicated data", null)]
        public async global::System.Threading.Tasks.Task AddNewSkillWithInvalidDetails(string testCaseID, string skill, string level, string message, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "negative"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            string[] tagsOfScenario = @__tags;
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("testCaseID", testCaseID);
            argumentsOfScenario.Add("skill", skill);
            argumentsOfScenario.Add("level", level);
            argumentsOfScenario.Add("message", message);
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Add new skill with invalid details", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 28
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 9
await this.FeatureBackgroundAsync();
#line hidden
#line 29
await testRunner.GivenAsync("I am in the skill section of my profile", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 30
await testRunner.WhenAsync(string.Format("I add new \"{0}\" and \"{1}\"", skill, level), ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 31
await testRunner.ThenAsync(string.Format("an error \"{0}\" should appear", message), ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Edit skill record with valid details")]
        [NUnit.Framework.CategoryAttribute("positive")]
        [NUnit.Framework.TestCaseAttribute("TC043", "Writing", "Technical Writing", "Expert", "Expert", "has been updated to your skills", null)]
        public async global::System.Threading.Tasks.Task EditSkillRecordWithValidDetails(string testCaseID, string skillOld, string skillNew, string levelOld, string levelNew, string message, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "positive"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            string[] tagsOfScenario = @__tags;
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("testCaseID", testCaseID);
            argumentsOfScenario.Add("skillOld", skillOld);
            argumentsOfScenario.Add("skillNew", skillNew);
            argumentsOfScenario.Add("levelOld", levelOld);
            argumentsOfScenario.Add("levelNew", levelNew);
            argumentsOfScenario.Add("message", message);
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Edit skill record with valid details", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 43
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 9
await this.FeatureBackgroundAsync();
#line hidden
#line 44
await testRunner.GivenAsync("I am in the skill section of my profile", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 45
await testRunner.AndAsync(string.Format("I verify the skill \"{0}\" with level \"{1}\" exists", skillOld, levelOld), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 46
await testRunner.WhenAsync(string.Format("I edit \"{0}\" to \"{1}\" and \"{2}\" to \"{3}\"", skillOld, skillNew, levelOld, levelNew), ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 47
await testRunner.ThenAsync(string.Format("successful update message \"{0}\" \"{1}\" should be displayed", skillNew, message), ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 48
await testRunner.AndAsync(string.Format("updated \"{0}\" and \"{1}\" should be shown  in the list", skillNew, levelNew), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Edit skill record with invalid details")]
        [NUnit.Framework.CategoryAttribute("negative")]
        [NUnit.Framework.TestCaseAttribute("TC044", "Communication", "", "Intermediate", "Expert", "Please enter skill and experience level", null)]
        [NUnit.Framework.TestCaseAttribute("TC045", "Communication", "Public Speaking", "Intermediate", "Skill Level", "Please enter skill and experience level", null)]
        [NUnit.Framework.TestCaseAttribute("TC046", "Communication", "Technical Writing", "Intermediate", "Expert", "This skill is already added to your skill list.", null)]
        public async global::System.Threading.Tasks.Task EditSkillRecordWithInvalidDetails(string testCaseID, string skillOld, string skillNew, string levelOld, string levelNew, string message, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "negative"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            string[] tagsOfScenario = @__tags;
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("testCaseID", testCaseID);
            argumentsOfScenario.Add("skillOld", skillOld);
            argumentsOfScenario.Add("skillNew", skillNew);
            argumentsOfScenario.Add("levelOld", levelOld);
            argumentsOfScenario.Add("levelNew", levelNew);
            argumentsOfScenario.Add("message", message);
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Edit skill record with invalid details", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 56
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 9
await this.FeatureBackgroundAsync();
#line hidden
#line 57
await testRunner.GivenAsync("I am in the skill section of my profile", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 58
await testRunner.AndAsync(string.Format("I verify the skill \"{0}\" with level \"{1}\" exists", skillOld, levelOld), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 59
await testRunner.WhenAsync(string.Format("I edit \"{0}\" to \"{1}\" and \"{2}\" to \"{3}\"", skillOld, skillNew, levelOld, levelNew), ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 60
await testRunner.ThenAsync(string.Format("an error \"{0}\" should be displayed", message), ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Delete skill record")]
        [NUnit.Framework.TestCaseAttribute("TC050", "Communication", "Intermediate", "has been deleted", null)]
        public async global::System.Threading.Tasks.Task DeleteSkillRecord(string testCaseID, string skill, string level, string message, string[] exampleTags)
        {
            string[] tagsOfScenario = exampleTags;
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("testCaseID", testCaseID);
            argumentsOfScenario.Add("skill", skill);
            argumentsOfScenario.Add("level", level);
            argumentsOfScenario.Add("message", message);
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Delete skill record", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 69
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 9
await this.FeatureBackgroundAsync();
#line hidden
#line 70
await testRunner.GivenAsync("I am in the skill section of my profile", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 71
await testRunner.AndAsync(string.Format("I verify the skill \"{0}\" with level \"{1}\" exists", skill, level), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 72
await testRunner.WhenAsync(string.Format("I delete the existing  \"{0}\" with \"{1}\" record", skill, level), ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 73
await testRunner.ThenAsync(string.Format("successful deletion  \"{0}\"  \"{1}\" should be displayed", skill, message), ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 74
await testRunner.AndAsync(string.Format("the \"{0}\" with \"{1}\" record should be removed from the list", skill, level), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
    }
}
#pragma warning restore
#endregion
